#deploy the workflow and the mother-app using the latest build
#kc apply -f ./deploy/app/application.yaml -n argo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mother-app
  namespace: argo
spec:
  project: default

  destination:
    namespace: argo
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true

  source:
    repoURL: https://github.com:mr-saoirse/funkyprompt.git
    targetRevision: HEAD
    path: deploy/app
    #this overrides the kustomize images
