apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: funky-app
spec:
  project: default
  source:
    repoURL: https://github.com/mr-saoirse/funkyprompt.git
    path: deploy/apps/mr-funky
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
