#to test before hading over to argo
#kustomize build app
#kubectl apply -k mr-funky
#ways to set with argo
#1. argocd app set staging --kustomize-image
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - argoKinds.yaml
resources:
  - uber-workflow.yaml
  - mother-app.yaml
images:
  - name: 286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test
    newTag: "funky-0.3.311"
