#see https://github.com/pypa/gh-action-pypi-publish for pypi notes
#tried pre with this https://github.com/mtkennerly/poetry-dynamic-versioning
#https://nadeauinnovations.com/post/2020/08/one-version-to-rule-them-all-keeping-your-python-package-version-number-in-sync-with-git-and-poetry/
name: BuildFUNKY
#build and release if semantic version changes on a tagged release
on:
  push:
    branches:
      - main
    paths:
      - "funkyprompt/**"
    # tags:
    #   #build when the tag is pushed with git tag 0.1.X & git push --tags
    #   - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-it:
    #look into how this works and get the tag as var
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/funkyprompt/
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    concurrency: release
    steps:
      - uses: actions/checkout@v3
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      # - name: Python Semantic Release
      #   uses: python-semantic-release/python-semantic-release@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
